export interface CountryCode {
  name: string;
  iso: string;
  dialCode: string;
  flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { name: 'Cameroun', iso: 'CM', dialCode: '+237', flag: '🇨🇲' },
  { name: 'République Démocratique du Congo', iso: 'CD', dialCode: '+243', flag: '🇨🇩' },
  { name: 'Congo', iso: 'CG', dialCode: '+242', flag: '🇨🇬' },
  { name: 'Gabon', iso: 'GA', dialCode: '+241', flag: '🇬🇦' },
  { name: 'Tchad', iso: 'TD', dialCode: '+235', flag: '🇹🇩' },
  { name: 'République Centrafricaine', iso: 'CF', dialCode: '+236', flag: '🇨🇫' },
  { name: 'Guinée Équatoriale', iso: 'GQ', dialCode: '+240', flag: '🇬🇶' },
  { name: 'Nigeria', iso: 'NG', dialCode: '+234', flag: '🇳🇬' },
  { name: 'Ghana', iso: 'GH', dialCode: '+233', flag: '🇬🇭' },
  { name: 'Côte d\'Ivoire', iso: 'CI', dialCode: '+225', flag: '🇨🇮' },
  { name: 'Sénégal', iso: 'SN', dialCode: '+221', flag: '🇸🇳' },
  { name: 'Mali', iso: 'ML', dialCode: '+223', flag: '🇲🇱' },
  { name: 'Burkina Faso', iso: 'BF', dialCode: '+226', flag: '🇧🇫' },
  { name: 'Bénin', iso: 'BJ', dialCode: '+229', flag: '🇧🇯' },
  { name: 'Togo', iso: 'TG', dialCode: '+228', flag: '🇹🇬' },
  { name: 'Niger', iso: 'NE', dialCode: '+227', flag: '🇳🇪' },
  { name: 'Guinée', iso: 'GN', dialCode: '+224', flag: '🇬🇳' },
  { name: 'Kenya', iso: 'KE', dialCode: '+254', flag: '🇰🇪' },
  { name: 'Tanzanie', iso: 'TZ', dialCode: '+255', flag: '🇹🇿' },
  { name: 'Ouganda', iso: 'UG', dialCode: '+256', flag: '🇺🇬' },
  { name: 'Rwanda', iso: 'RW', dialCode: '+250', flag: '🇷🇼' },
  { name: 'Burundi', iso: 'BI', dialCode: '+257', flag: '🇧🇮' },
  { name: 'Éthiopie', iso: 'ET', dialCode: '+251', flag: '🇪🇹' },
  { name: 'Afrique du Sud', iso: 'ZA', dialCode: '+27', flag: '🇿🇦' },
  { name: 'Égypte', iso: 'EG', dialCode: '+20', flag: '🇪🇬' },
  { name: 'Maroc', iso: 'MA', dialCode: '+212', flag: '🇲🇦' },
  { name: 'Algérie', iso: 'DZ', dialCode: '+213', flag: '🇩🇿' },
  { name: 'Tunisie', iso: 'TN', dialCode: '+216', flag: '🇹🇳' },
  { name: 'Angola', iso: 'AO', dialCode: '+244', flag: '🇦🇴' },
  { name: 'Zambie', iso: 'ZM', dialCode: '+260', flag: '🇿🇲' },
  { name: 'Zimbabwe', iso: 'ZW', dialCode: '+263', flag: '🇿🇼' },
  { name: 'France', iso: 'FR', dialCode: '+33', flag: '🇫🇷' },
  { name: 'Belgique', iso: 'BE', dialCode: '+32', flag: '🇧🇪' },
  { name: 'Suisse', iso: 'CH', dialCode: '+41', flag: '🇨🇭' },
  { name: 'Allemagne', iso: 'DE', dialCode: '+49', flag: '🇩🇪' },
  { name: 'Royaume-Uni', iso: 'GB', dialCode: '+44', flag: '🇬🇧' },
  { name: 'Espagne', iso: 'ES', dialCode: '+34', flag: '🇪🇸' },
  { name: 'Italie', iso: 'IT', dialCode: '+39', flag: '🇮🇹' },
  { name: 'Portugal', iso: 'PT', dialCode: '+351', flag: '🇵🇹' },
  { name: 'Pays-Bas', iso: 'NL', dialCode: '+31', flag: '🇳🇱' },
  { name: 'Canada', iso: 'CA', dialCode: '+1', flag: '🇨🇦' },
  { name: 'États-Unis', iso: 'US', dialCode: '+1', flag: '🇺🇸' },
  { name: 'Brésil', iso: 'BR', dialCode: '+55', flag: '🇧🇷' },
  { name: 'Chine', iso: 'CN', dialCode: '+86', flag: '🇨🇳' },
  { name: 'Inde', iso: 'IN', dialCode: '+91', flag: '🇮🇳' },
  { name: 'Émirats Arabes Unis', iso: 'AE', dialCode: '+971', flag: '🇦🇪' },
  { name: 'Arabie Saoudite', iso: 'SA', dialCode: '+966', flag: '🇸🇦' },
  { name: 'Turquie', iso: 'TR', dialCode: '+90', flag: '🇹🇷' },
  { name: 'Liban', iso: 'LB', dialCode: '+961', flag: '🇱🇧' },
  { name: 'Japon', iso: 'JP', dialCode: '+81', flag: '🇯🇵' },
  { name: 'Corée du Sud', iso: 'KR', dialCode: '+82', flag: '🇰🇷' },
  { name: 'Australie', iso: 'AU', dialCode: '+61', flag: '🇦🇺' },
  { name: 'Russie', iso: 'RU', dialCode: '+7', flag: '🇷🇺' },
  { name: 'Mexique', iso: 'MX', dialCode: '+52', flag: '🇲🇽' },
  { name: 'Argentine', iso: 'AR', dialCode: '+54', flag: '🇦🇷' },
  { name: 'Madagascar', iso: 'MG', dialCode: '+261', flag: '🇲🇬' },
  { name: 'Maurice', iso: 'MU', dialCode: '+230', flag: '🇲🇺' },
  { name: 'Comores', iso: 'KM', dialCode: '+269', flag: '🇰🇲' },
  { name: 'Djibouti', iso: 'DJ', dialCode: '+253', flag: '🇩🇯' },
  { name: 'Soudan', iso: 'SD', dialCode: '+249', flag: '🇸🇩' },
  { name: 'Libye', iso: 'LY', dialCode: '+218', flag: '🇱🇾' },
];